DROP TABLE IF EXISTS stock_snapshots;
ALTER TABLE stocks DROP COLUMN IF EXISTS liquidity_usd, DROP COLUMN IF EXISTS vol_24h_usd, DROP COLUMN IF EXISTS vol_1h_usd,
  DROP COLUMN IF EXISTS buys_24h, DROP COLUMN IF EXISTS sells_24h, DROP COLUMN IF EXISTS mcap_usd, DROP COLUMN IF EXISTS change_1h,
  DROP COLUMN IF EXISTS mark_usd, DROP COLUMN IF EXISTS premium_pct, DROP COLUMN IF EXISTS mark_valuation,
  DROP COLUMN IF EXISTS implied_valuation, DROP COLUMN IF EXISTS supply;
